name = "FoXy"
version = "0.0.8"
author = "Stefano Zaghi"
copyright = "Copyright © 2016, Stefano Zaghi"
license = "Multiple licenses"
description = "Fortran XML parser for poor people"
maintainer = "Stefano Zaghi"
homepage = "https://github.com/Fortran-FOSS-Programmers/FoXy"

[library]
source-dir = "src/lib"

[install]
library = true

[dependencies]
[dependencies.StringiFor]
git = "https://github.com/szaghi/StringiFor"
branch = "master"

[dependencies.PENF]
git = "https://github.com/szaghi/PENF"
branch = "master"
